name: test
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          # Set CC_TEST_REPORTER_ID as secret of your repo
          CC_TEST_REPORTER_ID: 24c5c57e3c6e5d5ce2c1e335516b8c8c9c105c837a8856111d55293477ea8444
          JACOCO_SOURCE_PATH: "${{github.workspace}}/src/main/java"
        with:
          # The report file must be there, otherwise Code Climate won't find it
          coverageCommand: ./gradlew jacocoTestReport
          coverageLocations: "${{github.workspace}}/build/reports/jacoco/test/jacocoTestReport.xml:jacoco"
